### ISSUE TITLE
There's an issue with building or running the ssi-api docker image. 

### ISSUE THREAD

**Issue by dwjohnston** [460degrees/acme-university-demo#22]
(I think). It's to do with docker caching. 

What is meant to happen is that at container runtime (the CMD command), is mean to run the provision_agent.py script - with a fixed seed and password. This sets up the wallet on the docker container. 

Currently something wierd is happening where if you rebuild the docker image, it is fine, bu then subsequent runs of it fail with 'DID already exists'. 

Anyway - worth looking into.

**Comment by jackdwyer** [comment]
This is expected behavior from libcvx/libindy & the included [provision_agent_keys.py](https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/scripts/provision_agent_keys.py) script.

When the provision script is first ran it calls libcvx then libindy which generates the wallet for the provided `${WALLET_NAME}` etc to `${HOME}/.indy_client`

If the wallet exists the provisioning fails, causing the
```could not register agent, see log
{
  "provisioned": false,
  "provisioned_status": "Failed: Could not register agent, see log\n"
}
```
We could guard the provision script by checking if the directory exists, or pass in the wallet in at runtime when the ssi-api is started.

Luckily its only a warning so we can safely ignore it for now.
